export default {
 en: {
  brandConcept:'Product strategy · Development · Manufacturing · Supply chain', makerConcept:'Product development · Positioning · Representation · International business development', secondaryHeading:'Work with me', secondaryLink:'Join the specialist network', manufacturingStrategy:'Manufacturing Strategy', brandIntro:'Tell me what you are developing and where you need support.', ecosystem:['Brands','Manufacturers','Specialists','Markets'], ecosystemTitle:'Connecting product, manufacturing and market.',
  developmentTitle:'Development & positioning', developmentIntro:'Develop products that show what your factory can make for premium and luxury brands.', representationTitle:'Manufacturer representation & business development', representationIntro:'I selectively represent manufacturers with the technical capability and product quality to work with international brands.', representationBody:'Selected manufacturers may join my network and be introduced to brands or projects where there is a suitable fit.', selection:'I assess each manufacturer’s quality, technical capability, reliability and suitability. Terms are agreed privately. Applying does not guarantee representation or introductions.', apply:'Apply for representation',
  brandEnquiry:{title:'Brand enquiry',intro:'Describe your project and the support you need.'}, manufacturerApplication:{title:'Manufacturer application',intro:'Describe your factory’s capabilities and the markets you want to develop. I review each application individually.'}, specialistApplication:{title:'Specialist network application',intro:'Send your experience and the work you would like to contribute to. I select specialists for individual assignments.'},
 },
 fr: {
  brandConcept:'Stratégie produit · Développement · Fabrication · Supply chain',makerConcept:'Développement produit · Positionnement · Représentation · Développement commercial international',secondaryHeading:'Travailler avec moi',secondaryLink:'Rejoindre le réseau de spécialistes',manufacturingStrategy:'Stratégie de fabrication',brandIntro:'Présentez votre projet et les points sur lesquels vous avez besoin d’appui.',ecosystem:['Marques','Fabricants','Spécialistes','Marchés'],ecosystemTitle:'Relier le produit, la fabrication et le marché.',
  developmentTitle:'Développement & positionnement',developmentIntro:'Développer des produits qui montrent ce que votre usine peut fabriquer pour les marques premium et de luxe.',representationTitle:'Représentation des fabricants & développement commercial',representationIntro:'Je représente une sélection de fabricants dont les capacités techniques et la qualité des produits répondent aux besoins des marques internationales.',representationBody:'Les fabricants sélectionnés peuvent rejoindre mon réseau et être présentés à des marques ou à des projets correspondant à leurs capacités.',selection:'J’évalue la qualité, les capacités techniques, la fiabilité et l’adéquation de chaque fabricant. Les conditions sont convenues en privé. Une candidature ne garantit ni représentation ni mise en relation.',apply:'Proposer votre candidature',
  brandEnquiry:{title:'Votre projet de marque',intro:'Décrivez votre projet et l’accompagnement recherché.'},manufacturerApplication:{title:'Candidature fabricant',intro:'Présentez les capacités de votre usine et les marchés que vous souhaitez développer. J’étudie chaque candidature individuellement.'},specialistApplication:{title:'Candidature au réseau de spécialistes',intro:'Présentez votre expérience et les travaux auxquels vous souhaitez contribuer. Je sélectionne les spécialistes pour chaque mission.'},
 },
 pt: {
  brandConcept:'Estratégia de produto · Desenvolvimento · Fabricação · Cadeia de suprimentos',makerConcept:'Desenvolvimento de produto · Posicionamento · Representação · Negócios internacionais',secondaryHeading:'Trabalhe comigo',secondaryLink:'Entrar para a rede de especialistas',manufacturingStrategy:'Estratégia de fabricação',brandIntro:'Descreva seu projeto e o apoio de que precisa.',ecosystem:['Marcas','Fabricantes','Especialistas','Mercados'],ecosystemTitle:'Conectando produto, fabricação e mercado.',
  developmentTitle:'Desenvolvimento & posicionamento',developmentIntro:'Desenvolver produtos que mostrem o que sua fábrica pode produzir para marcas premium e de luxo.',representationTitle:'Representação de fabricantes & desenvolvimento de negócios',representationIntro:'Represento uma seleção de fabricantes com capacidade técnica e qualidade de produto para trabalhar com marcas internacionais.',representationBody:'Os fabricantes selecionados podem integrar minha rede e ser apresentados a marcas ou projetos compatíveis com suas capacidades.',selection:'Avalio a qualidade, a capacidade técnica, a confiabilidade e a adequação de cada fabricante. As condições são acordadas em privado. A candidatura não garante representação ou apresentações.',apply:'Enviar candidatura',
  brandEnquiry:{title:'Consulta para marcas',intro:'Descreva seu projeto e o apoio de que precisa.'},manufacturerApplication:{title:'Candidatura de fabricante',intro:'Apresente as capacidades da sua fábrica e os mercados que deseja desenvolver. Analiso cada candidatura individualmente.'},specialistApplication:{title:'Candidatura à rede de especialistas',intro:'Envie sua experiência e os trabalhos de que gostaria de participar. Seleciono especialistas para cada projeto.'},
 },
 it: {
  brandConcept:'Strategia di prodotto · Sviluppo · Manifattura · Filiera',makerConcept:'Sviluppo prodotto · Posizionamento · Rappresentanza · Sviluppo commerciale internazionale',secondaryHeading:'Collabora con me',secondaryLink:'Entra nel network di specialisti',manufacturingStrategy:'Strategia produttiva',brandIntro:'Descrivi il progetto e il supporto di cui hai bisogno.',ecosystem:['Brand','Produttori','Specialisti','Mercati'],ecosystemTitle:'Connettere prodotto, manifattura e mercato.',
  developmentTitle:'Sviluppo e posizionamento',developmentIntro:'Sviluppare prodotti che mostrino ciò che la tua fabbrica può realizzare per i brand premium e del lusso.',representationTitle:'Rappresentanza dei produttori e sviluppo commerciale',representationIntro:'Rappresento una selezione di produttori con le capacità tecniche e la qualità di prodotto necessarie per lavorare con brand internazionali.',representationBody:'I produttori selezionati possono entrare nella mia rete ed essere presentati a brand o progetti adatti alle loro capacità.',selection:'Valuto la qualità, le capacità tecniche, l’affidabilità e l’idoneità di ogni produttore. Le condizioni vengono concordate privatamente. La candidatura non garantisce rappresentanza o introduzioni.',apply:'Invia la candidatura',
  brandEnquiry:{title:'Richiesta per i brand',intro:'Descrivi il progetto e il supporto che cerchi.'},manufacturerApplication:{title:'Candidatura produttori',intro:'Presenta le capacità della tua fabbrica e i mercati che vuoi sviluppare. Esamino ogni candidatura individualmente.'},specialistApplication:{title:'Candidatura al network di specialisti',intro:'Presenta la tua esperienza e il lavoro a cui vorresti contribuire. Scelgo gli specialisti per ogni incarico.'},
 },
 es: {
  brandConcept:'Estrategia de producto · Desarrollo · Fabricación · Cadena de suministro',makerConcept:'Desarrollo de producto · Posicionamiento · Representación · Negocio internacional',secondaryHeading:'Trabaja conmigo',secondaryLink:'Unirse a la red de especialistas',manufacturingStrategy:'Estrategia de fabricación',brandIntro:'Describe el proyecto y el apoyo que necesitas.',ecosystem:['Marcas','Fabricantes','Especialistas','Mercados'],ecosystemTitle:'Conectar producto, fabricación y mercado.',
  developmentTitle:'Desarrollo y posicionamiento',developmentIntro:'Desarrollar productos que muestren lo que tu fábrica puede producir para marcas premium y de lujo.',representationTitle:'Representación de fabricantes y desarrollo de negocio',representationIntro:'Represento a una selección de fabricantes con la capacidad técnica y la calidad de producto necesarias para trabajar con marcas internacionales.',representationBody:'Los fabricantes seleccionados pueden formar parte de mi red y ser presentados a marcas o proyectos adecuados a sus capacidades.',selection:'Evalúo la calidad, la capacidad técnica, la fiabilidad y la idoneidad de cada fabricante. Las condiciones se acuerdan en privado. La candidatura no garantiza representación ni contactos.',apply:'Presentar candidatura',
  brandEnquiry:{title:'Consulta para marcas',intro:'Describe tu proyecto y el apoyo que buscas.'},manufacturerApplication:{title:'Solicitud para fabricantes',intro:'Presenta las capacidades de tu fábrica y los mercados que quieres desarrollar. Reviso cada candidatura individualmente.'},specialistApplication:{title:'Solicitud para la red de especialistas',intro:'Envía tu experiencia y el trabajo en el que te gustaría participar. Selecciono a los especialistas para cada encargo.'},
 },
 zh: {
  brandConcept:'产品策略 · 产品开发 · 生产制造 · 供应链',makerConcept:'产品开发 · 市场定位 · 商务代理 · 国际商务拓展',secondaryHeading:'与我合作',secondaryLink:'加入专业协作网络',manufacturingStrategy:'制造策略',brandIntro:'请说明您的项目及所需支持。',ecosystem:['品牌','制造商','专业人才','市场'],ecosystemTitle:'连接产品、制造与市场。',
  developmentTitle:'产品开发与市场定位',developmentIntro:'开发能向高端与奢侈品牌展示工厂制造能力的产品。',representationTitle:'制造商商务代理与业务拓展',representationIntro:'我选择具备相应技术能力和产品质量、能够与国际品牌合作的制造商进行代理。',representationBody:'入选的制造商可加入我的合作网络，并有机会对接符合其能力的品牌或项目。',selection:'我评估每家制造商的质量、技术能力、履约可靠性及合作适配度。合作条款由双方私下协商。申请不保证获得代理或业务对接。',apply:'提交合作申请',
  brandEnquiry:{title:'品牌项目咨询',intro:'请介绍您的项目及所需支持。'},manufacturerApplication:{title:'制造商合作申请',intro:'请介绍工厂能力及希望拓展的市场。我会逐一评估申请。'},specialistApplication:{title:'专业协作网络申请',intro:'请介绍您的经验和希望参与的工作。我根据每项委托选择专业人员。'},
 },
};
