export default {
 en: {
  brandConcept:'Product strategy · Development · Manufacturing · Supply chain', makerConcept:'Product development · Positioning · Representation · International business development', secondaryHeading:'Interested in working with us?', secondaryLink:'Join our specialist network', manufacturingStrategy:'Manufacturing Strategy', brandIntro:'Start with the challenge. Together, we define what your business needs and build the right product, manufacturing and specialist support around it.', ecosystem:['Brands','Manufacturers','Specialists','Markets'], ecosystemTitle:'Connecting product, manufacturing and market.',
  developmentTitle:'Development & positioning', developmentIntro:'Shape your technical capabilities into commercially relevant products and a clear, compelling offer for the luxury and premium fashion market.', representationTitle:'Manufacturer representation & business development', representationIntro:'We selectively represent manufacturing partners with strong technical capabilities, product quality and international potential.', representationBody:'Selected manufacturers can become part of our international manufacturing network and may be introduced to relevant brands, projects and commercial opportunities across our markets.', selection:'Selection considers quality, technical capability, reliability and commercial relevance. Each potential partnership is assessed individually; commercial arrangements are negotiated privately. Applying does not guarantee representation or introductions.', apply:'Apply to join our manufacturing network',
  brandEnquiry:{title:'Brand enquiry',intro:'Tell us about your challenge. A few details will help us begin a focused conversation about the right solution.'}, manufacturerApplication:{title:'Manufacturer application',intro:'Introduce your company, capabilities and commercial ambitions. Applications support an individual assessment of potential manufacturing partnerships.'}, specialistApplication:{title:'Specialist network application',intro:'Share your expertise and the work you would like to contribute to. Specialists are selected according to the requirements of individual assignments.'},
 },
 fr: {
  brandConcept:'Stratégie produit · Développement · Fabrication · Supply chain',makerConcept:'Développement produit · Positionnement · Représentation · Développement commercial international',secondaryHeading:'Vous souhaitez collaborer avec nous ?',secondaryLink:'Rejoindre notre réseau de spécialistes',manufacturingStrategy:'Stratégie de fabrication',brandIntro:'Tout commence par votre enjeu. Ensemble, nous définissons les besoins de votre activité et construisons l’accompagnement adapté en produit, fabrication et expertises spécialisées.',ecosystem:['Marques','Fabricants','Spécialistes','Marchés'],ecosystemTitle:'Relier le produit, la fabrication et le marché.',
  developmentTitle:'Développement & positionnement',developmentIntro:'Transformer vos capacités techniques en produits commercialement pertinents et en une offre claire et convaincante pour la mode premium et le luxe.',representationTitle:'Représentation des fabricants & développement commercial',representationIntro:'Nous représentons de manière sélective des partenaires industriels reconnus pour leurs capacités techniques, la qualité de leurs produits et leur potentiel international.',representationBody:'Les fabricants sélectionnés peuvent intégrer notre réseau international et être mis en relation avec des marques, des projets et des opportunités commerciales pertinents sur nos marchés.',selection:'La sélection tient compte de la qualité, des capacités techniques, de la fiabilité et de la pertinence commerciale. Chaque partenariat est étudié individuellement et les modalités commerciales sont négociées en privé. Une candidature ne garantit ni représentation ni mise en relation.',apply:'Candidater à notre réseau de fabricants',
  brandEnquiry:{title:'Votre projet de marque',intro:'Parlez-nous de votre enjeu. Quelques informations nous permettront d’engager un échange ciblé sur la solution adaptée.'},manufacturerApplication:{title:'Candidature fabricant',intro:'Présentez votre entreprise, vos capacités et vos ambitions commerciales. Chaque candidature permet d’étudier individuellement les possibilités de partenariat industriel.'},specialistApplication:{title:'Candidature au réseau de spécialistes',intro:'Présentez votre expertise et les projets auxquels vous souhaitez contribuer. Les spécialistes sont sélectionnés selon les besoins de chaque mission.'},
 },
 pt: {
  brandConcept:'Estratégia de produto · Desenvolvimento · Fabricação · Cadeia de suprimentos',makerConcept:'Desenvolvimento de produto · Posicionamento · Representação · Negócios internacionais',secondaryHeading:'Quer trabalhar conosco?',secondaryLink:'Faça parte da nossa rede de especialistas',manufacturingStrategy:'Estratégia de fabricação',brandIntro:'O ponto de partida é o seu desafio. Juntos, definimos o que o negócio precisa e construímos o apoio adequado em produto, fabricação e competências especializadas.',ecosystem:['Marcas','Fabricantes','Especialistas','Mercados'],ecosystemTitle:'Conectando produto, fabricação e mercado.',
  developmentTitle:'Desenvolvimento & posicionamento',developmentIntro:'Transforme suas competências técnicas em produtos comercialmente relevantes e em uma oferta clara e convincente para o mercado de moda premium e de luxo.',representationTitle:'Representação de fabricantes & desenvolvimento de negócios',representationIntro:'Representamos de forma seletiva parceiros de fabricação com capacidade técnica, qualidade de produto e potencial internacional.',representationBody:'Os fabricantes selecionados podem integrar nossa rede internacional e ser apresentados a marcas, projetos e oportunidades comerciais relevantes nos mercados em que atuamos.',selection:'A seleção considera qualidade, capacidade técnica, confiabilidade e relevância comercial. Cada parceria é avaliada individualmente e as condições comerciais são negociadas de forma privada. A candidatura não garante representação ou apresentações comerciais.',apply:'Candidate-se à nossa rede de fabricantes',
  brandEnquiry:{title:'Consulta para marcas',intro:'Conte-nos sobre seu desafio. Algumas informações nos ajudam a iniciar uma conversa objetiva sobre a solução adequada.'},manufacturerApplication:{title:'Candidatura de fabricante',intro:'Apresente sua empresa, suas competências e suas ambições comerciais. Cada candidatura permite uma avaliação individual das possibilidades de parceria de fabricação.'},specialistApplication:{title:'Candidatura à rede de especialistas',intro:'Compartilhe sua experiência e os trabalhos para os quais gostaria de contribuir. Os especialistas são selecionados conforme as necessidades de cada projeto.'},
 },
 it: {
  brandConcept:'Strategia di prodotto · Sviluppo · Manifattura · Filiera',makerConcept:'Sviluppo prodotto · Posizionamento · Rappresentanza · Sviluppo commerciale internazionale',secondaryHeading:'Ti interessa collaborare con noi?',secondaryLink:'Entra nel nostro network di specialisti',manufacturingStrategy:'Strategia produttiva',brandIntro:'Partiamo dalla tua sfida. Insieme, definiamo ciò di cui la tua attività ha bisogno e costruiamo il supporto adatto in prodotto, manifattura e competenze specialistiche.',ecosystem:['Brand','Produttori','Specialisti','Mercati'],ecosystemTitle:'Connettere prodotto, manifattura e mercato.',
  developmentTitle:'Sviluppo e posizionamento',developmentIntro:'Trasformare le capacità tecniche in prodotti commercialmente rilevanti e in un’offerta chiara e convincente per il mercato della moda premium e del lusso.',representationTitle:'Rappresentanza dei produttori e sviluppo commerciale',representationIntro:'Rappresentiamo in modo selettivo partner produttivi con solide competenze tecniche, qualità di prodotto e potenziale internazionale.',representationBody:'I produttori selezionati possono entrare nel nostro network manifatturiero internazionale ed essere presentati a brand, progetti e opportunità commerciali pertinenti nei nostri mercati.',selection:'La selezione considera qualità, competenze tecniche, affidabilità e rilevanza commerciale. Ogni possibile partnership viene valutata singolarmente e gli accordi commerciali sono negoziati in via riservata. La candidatura non garantisce rappresentanza o introduzioni commerciali.',apply:'Candidati al nostro network di produttori',
  brandEnquiry:{title:'Richiesta per i brand',intro:'Raccontaci la tua sfida. Bastano alcune informazioni per avviare un confronto mirato sulla soluzione più adatta.'},manufacturerApplication:{title:'Candidatura produttori',intro:'Presenta la tua azienda, le tue capacità e le tue ambizioni commerciali. Le candidature consentono di valutare singolarmente le opportunità di partnership produttiva.'},specialistApplication:{title:'Candidatura al network di specialisti',intro:'Condividi le tue competenze e i progetti a cui vorresti contribuire. Gli specialisti vengono selezionati in base alle esigenze dei singoli incarichi.'},
 },
 es: {
  brandConcept:'Estrategia de producto · Desarrollo · Fabricación · Cadena de suministro',makerConcept:'Desarrollo de producto · Posicionamiento · Representación · Negocio internacional',secondaryHeading:'¿Te interesa colaborar con nosotros?',secondaryLink:'Únete a nuestra red de especialistas',manufacturingStrategy:'Estrategia de fabricación',brandIntro:'Empezamos por tu reto. Juntos, definimos lo que necesita tu negocio y construimos el apoyo adecuado en producto, fabricación y conocimientos especializados.',ecosystem:['Marcas','Fabricantes','Especialistas','Mercados'],ecosystemTitle:'Conectar producto, fabricación y mercado.',
  developmentTitle:'Desarrollo y posicionamiento',developmentIntro:'Transforma tus capacidades técnicas en productos comercialmente relevantes y en una propuesta clara y convincente para el mercado de moda premium y de lujo.',representationTitle:'Representación de fabricantes y desarrollo de negocio',representationIntro:'Representamos de forma selectiva a socios de fabricación con sólidas capacidades técnicas, calidad de producto y potencial internacional.',representationBody:'Los fabricantes seleccionados pueden formar parte de nuestra red internacional y ser presentados a marcas, proyectos y oportunidades comerciales relevantes en nuestros mercados.',selection:'La selección considera calidad, capacidad técnica, fiabilidad y relevancia comercial. Cada posible colaboración se evalúa individualmente y las condiciones comerciales se negocian en privado. Presentar una candidatura no garantiza representación ni contactos comerciales.',apply:'Solicita unirte a nuestra red de fabricantes',
  brandEnquiry:{title:'Consulta para marcas',intro:'Cuéntanos tu reto. Unos pocos datos nos ayudarán a iniciar una conversación centrada en la solución adecuada.'},manufacturerApplication:{title:'Solicitud para fabricantes',intro:'Presenta tu empresa, tus capacidades y tus ambiciones comerciales. Las solicitudes permiten evaluar individualmente las posibles colaboraciones de fabricación.'},specialistApplication:{title:'Solicitud para la red de especialistas',intro:'Comparte tu experiencia y el trabajo al que te gustaría contribuir. Los especialistas se seleccionan según los requisitos de cada encargo.'},
 },
 zh: {
  brandConcept:'产品策略 · 产品开发 · 生产制造 · 供应链',makerConcept:'产品开发 · 市场定位 · 商务代理 · 国际商务拓展',secondaryHeading:'希望与我们合作？',secondaryLink:'加入我们的专业协作网络',manufacturingStrategy:'制造策略',brandIntro:'从您的业务挑战出发，共同明确需求，配置适合的产品、制造及专业支持方案。',ecosystem:['品牌','制造商','专业人才','市场'],ecosystemTitle:'连接产品、制造与市场。',
  developmentTitle:'产品开发与市场定位',developmentIntro:'将技术能力转化为具有商业价值的产品，以及面向高端与奢侈时尚市场、清晰且富有说服力的产品方案。',representationTitle:'制造商商务代理与业务拓展',representationIntro:'我们择优代理具备扎实技术能力、优质产品及国际发展潜力的制造合作伙伴。',representationBody:'入选的制造商可加入我们的国际制造合作网络，并有机会对接相关品牌、项目及目标市场的商业机会。',selection:'评估重点包括产品质量、技术能力、履约可靠性及商业匹配度。每项潜在合作均单独评估，商业条款由双方私下协商。提交申请并不保证获得代理或业务对接。',apply:'申请加入我们的制造合作网络',
  brandEnquiry:{title:'品牌项目咨询',intro:'请介绍您面临的挑战。简要信息有助于我们围绕适合的解决方案展开沟通。'},manufacturerApplication:{title:'制造商合作申请',intro:'请介绍贵公司的能力与商业目标。每份申请将用于单独评估潜在的制造合作机会。'},specialistApplication:{title:'专业协作网络申请',intro:'请介绍您的专业经验及希望参与的工作。我们根据各项委托的具体要求甄选专业人才。'},
 },
};
