const fieldIds=['name','company','role','email','website','categories','help','timing','budget','phone','country','city','specialisms','materials','machinery','moq','capacity','leadTimes','sampleRoom','currentMarkets','premiumExperience','clientExperience','certifications','compliance','targetMarkets','introduction','profileUrl','location','languages','expertise','years','availability','status','portfolio','linkedin','rate'];
const groupIds=['project','company','capabilities','production','experience','standards','ambitions','profile','expertise'];
const map=(ids,labels)=>Object.fromEntries(ids.map((id,i)=>[id,labels[i]]));
const form=(copy)=>({...copy,labels:map(fieldIds,copy.labels),groups:map(groupIds,copy.groups)});
export default {
 en:form({
 titles:{brandEnquiry:'Brand enquiry',manufacturerApplication:'Manufacturer application',specialistApplication:'Specialist network application'},
 labels:['Name','Brand / Company','Role / Position','Email','Website','Product categories','What can we help with?','Project timing','Indicative budget / Project scope','Phone / WeChat','Country','City','Manufacturing specialisms','Materials / Yarn expertise','Machinery / Specialist techniques','Minimum order quantity (MOQ)','Production capacity','Typical lead times','Sample room / Development capability','Markets worked in / Current markets','Premium / Luxury experience','Relevant client experience','Certifications','Sustainability / Compliance information','Markets you want to develop','Short introduction','Company profile / Presentation / Lookbook URL','Location','Languages','Area of expertise','Years of experience','Availability','Freelance / Company status','Portfolio URL','LinkedIn URL','Typical day rate / Project rate'],
 groups:['Your project','Company & contact','Technical capabilities','Production & development','Markets & experience','Standards & compliance','Commercial ambitions','Your profile','Your expertise'],
 intro:'This form prepares an email draft for you to review and send using your email app. The website does not send or store your details.',requiredNote:'Fields marked * are required. Other fields are optional.',optional:'optional',choose:'Select an area',consent:'I agree to share these details by email with MILENA PEREIRA LIMITED so it can assess and respond to my enquiry. I understand that this form does not send or store my information.',privacy:'Your entries remain in this page until you leave or refresh it. They are not saved to a database or browser storage. Once you send an email, its contents are handled through the email providers involved. For privacy enquiries, contact milena@milenapereira.co.',urlHint:'Use a complete http:// or https:// link. Documents are shared by URL; this website does not upload files.',experienceHint:'Share only experience and information you are authorised to disclose.',
 submit:{brandEnquiry:'Discuss a project',manufacturerApplication:'Submit manufacturer application',specialistApplication:'Submit specialist application'},beforeSubmit:'Next: review your email draft. Nothing is sent by this form.',errorTitle:'Please check the following fields.',errors:{required:'Please complete this field.',email:'Enter a valid email address.',url:'Enter a complete http:// or https:// URL without login details.',number:'Enter a number from 0 to 80.',tooLong:'Please use no more than {max} characters.',consent:'Please acknowledge how your enquiry will be handled.'},ready:'Your email draft is ready',notSent:'Nothing has been sent or stored by this website. Review the draft, then send it from your email app.',longDraft:'For this detailed application, copy the draft below and paste it into your email. The email link opens the recipient and subject only.',shortDraft:'Open the prepared email below, or copy the draft into your preferred email service.',openEmail:'Open email',copy:'Copy draft',copied:'Draft copied. Paste it into your email and send when ready.',copyError:'Copy was unavailable. Select and copy the draft below manually.',edit:'Edit details',draftLabel:'Your email draft',noScript:'To use the form, enable JavaScript. You can also email milena@milenapereira.co directly.'
 }),
 fr:form({
 titles:{brandEnquiry:'Demande de conseil pour une marque',manufacturerApplication:'Candidature fabricant',specialistApplication:'Candidature au réseau de spécialistes'},
 labels:['Nom','Marque / Entreprise','Fonction','E-mail','Site internet','Catégories de produits','Comment pouvons-nous vous accompagner ?','Calendrier du projet','Budget indicatif / Périmètre du projet','Téléphone / WeChat','Pays','Ville','Spécialités de fabrication','Expertise matières / Fils','Parc machines / Techniques spécifiques','Quantité minimale de commande (MOQ)','Capacité de production','Délais habituels','Bureau d’études / Capacité de développement','Marchés actuels / Expérience des marchés','Expérience dans le premium / Luxe','Expériences clients pertinentes','Certifications','Informations sur la durabilité / Conformité','Marchés que vous souhaitez développer','Présentation en quelques mots','Lien vers la présentation d’entreprise / Le lookbook','Localisation','Langues','Domaine d’expertise','Années d’expérience','Disponibilité','Statut indépendant / Société','Lien vers le portfolio','Lien LinkedIn','Tarif journalier / Forfait projet habituel'],
 groups:['Votre projet','Entreprise & contact','Capacités techniques','Production & développement','Marchés & expérience','Normes & conformité','Ambitions commerciales','Votre profil','Votre expertise'],
 intro:'Ce formulaire prépare un brouillon d’e-mail que vous pourrez relire et envoyer depuis votre messagerie. Le site n’envoie ni ne conserve vos informations.',requiredNote:'Les champs marqués * sont obligatoires. Les autres sont facultatifs.',optional:'facultatif',choose:'Sélectionnez un domaine',consent:'J’accepte de transmettre ces informations par e-mail à MILENA PEREIRA LIMITED afin que ma demande puisse être étudiée et recevoir une réponse. Je comprends que ce formulaire n’envoie ni ne conserve mes informations.',privacy:'Vos saisies restent sur cette page jusqu’à sa fermeture ou son actualisation. Elles ne sont enregistrées ni dans une base de données ni dans le stockage du navigateur. Après l’envoi d’un e-mail, son contenu est traité par les services de messagerie concernés. Pour toute question relative à la confidentialité : milena@milenapereira.co.',urlHint:'Indiquez un lien complet commençant par http:// ou https://. Les documents sont partagés par lien ; aucun fichier n’est téléversé sur ce site.',experienceHint:'Ne communiquez que les expériences et informations que vous êtes autorisé à divulguer.',
 submit:{brandEnquiry:'Parlons de votre projet',manufacturerApplication:'Envoyer une candidature fabricant',specialistApplication:'Envoyer une candidature spécialiste'},beforeSubmit:'Étape suivante : relire le brouillon d’e-mail. Ce formulaire n’envoie rien.',errorTitle:'Veuillez vérifier les champs suivants.',errors:{required:'Veuillez remplir ce champ.',email:'Saisissez une adresse e-mail valide.',url:'Saisissez une URL http:// ou https:// complète, sans identifiants de connexion.',number:'Saisissez un nombre compris entre 0 et 80.',tooLong:'Veuillez limiter votre réponse à {max} caractères.',consent:'Veuillez confirmer avoir compris le traitement de votre demande.'},ready:'Votre brouillon d’e-mail est prêt',notSent:'Ce site n’a rien envoyé ni enregistré. Relisez le brouillon, puis envoyez-le depuis votre messagerie.',longDraft:'Pour cette candidature détaillée, copiez le brouillon ci-dessous dans votre e-mail. Le lien renseigne uniquement le destinataire et l’objet.',shortDraft:'Ouvrez l’e-mail préparé ci-dessous ou copiez le brouillon dans votre messagerie habituelle.',openEmail:'Ouvrir l’e-mail',copy:'Copier le brouillon',copied:'Brouillon copié. Collez-le dans votre messagerie et envoyez-le lorsque vous êtes prêt.',copyError:'La copie automatique est indisponible. Sélectionnez et copiez le brouillon ci-dessous.',edit:'Modifier les informations',draftLabel:'Votre brouillon d’e-mail',noScript:'Activez JavaScript pour utiliser ce formulaire. Vous pouvez aussi écrire directement à milena@milenapereira.co.'
 }),
 pt:form({
 titles:{brandEnquiry:'Consulta para marcas',manufacturerApplication:'Candidatura de fabricante',specialistApplication:'Candidatura à rede de especialistas'},
 labels:['Nome','Marca / Empresa','Cargo / Função','E-mail','Site','Categorias de produto','Como podemos ajudar?','Prazo do projeto','Orçamento indicativo / Escopo do projeto','Telefone / WeChat','País','Cidade','Especialidades de fabricação','Conhecimento em materiais / Fios','Maquinário / Técnicas especializadas','Quantidade mínima de pedido (MOQ)','Capacidade de produção','Prazos habituais','Sala de amostras / Capacidade de desenvolvimento','Mercados atuais / Mercados de atuação','Experiência em premium / Luxo','Experiência relevante com clientes','Certificações','Informações de sustentabilidade / Conformidade','Mercados que deseja desenvolver','Breve apresentação','URL da apresentação da empresa / Lookbook','Localização','Idiomas','Área de especialidade','Anos de experiência','Disponibilidade','Atuação como freelancer / Empresa','URL do portfólio','URL do LinkedIn','Valor habitual de diária / Projeto'],
 groups:['Seu projeto','Empresa & contato','Competências técnicas','Produção & desenvolvimento','Mercados & experiência','Normas & conformidade','Ambições comerciais','Seu perfil','Sua especialidade'],
 intro:'Este formulário prepara um rascunho de e-mail para você revisar e enviar pelo seu aplicativo de e-mail. O site não envia nem armazena seus dados.',requiredNote:'Campos com * são obrigatórios. Os demais são opcionais.',optional:'opcional',choose:'Selecione uma área',consent:'Concordo em compartilhar estas informações por e-mail com MILENA PEREIRA LIMITED para que minha consulta seja avaliada e respondida. Entendo que este formulário não envia nem armazena meus dados.',privacy:'As informações preenchidas ficam nesta página até você sair ou recarregá-la. Elas não são salvas em banco de dados nem no armazenamento do navegador. Após o envio do e-mail, o conteúdo é tratado pelos provedores de e-mail envolvidos. Para questões de privacidade, escreva para milena@milenapereira.co.',urlHint:'Use um link completo iniciado por http:// ou https://. Os documentos são compartilhados por URL; este site não faz upload de arquivos.',experienceHint:'Compartilhe apenas experiências e informações que você tem autorização para divulgar.',
 submit:{brandEnquiry:'Vamos falar sobre seu projeto',manufacturerApplication:'Enviar candidatura de fabricante',specialistApplication:'Enviar candidatura de especialista'},beforeSubmit:'Próxima etapa: revisar o rascunho do e-mail. Nada é enviado por este formulário.',errorTitle:'Confira os campos abaixo.',errors:{required:'Preencha este campo.',email:'Informe um endereço de e-mail válido.',url:'Informe uma URL http:// ou https:// completa, sem dados de acesso.',number:'Informe um número entre 0 e 80.',tooLong:'Use no máximo {max} caracteres.',consent:'Confirme que entendeu como sua consulta será encaminhada.'},ready:'Seu rascunho de e-mail está pronto',notSent:'Nada foi enviado ou armazenado por este site. Revise o rascunho e envie pelo seu aplicativo de e-mail.',longDraft:'Para esta candidatura detalhada, copie o rascunho abaixo e cole no seu e-mail. O link preenche apenas o destinatário e o assunto.',shortDraft:'Abra o e-mail preparado abaixo ou copie o rascunho para o serviço de e-mail de sua preferência.',openEmail:'Abrir e-mail',copy:'Copiar rascunho',copied:'Rascunho copiado. Cole no seu e-mail e envie quando estiver pronto.',copyError:'Não foi possível copiar automaticamente. Selecione e copie o rascunho abaixo.',edit:'Editar informações',draftLabel:'Seu rascunho de e-mail',noScript:'Ative o JavaScript para usar o formulário. Você também pode escrever diretamente para milena@milenapereira.co.'
 }),
 it:form({
 titles:{brandEnquiry:'Richiesta per i brand',manufacturerApplication:'Candidatura produttori',specialistApplication:'Candidatura al network di specialisti'},
 labels:['Nome','Brand / Azienda','Ruolo / Posizione','Email','Sito web','Categorie di prodotto','Come possiamo aiutarti?','Tempistiche del progetto','Budget indicativo / Perimetro del progetto','Telefono / WeChat','Paese','Città','Specializzazioni produttive','Competenze su materiali / Filati','Macchinari / Lavorazioni specialistiche','Quantità minima d’ordine (MOQ)','Capacità produttiva','Tempi di consegna abituali','Reparto campionatura / Capacità di sviluppo','Mercati attuali / Mercati in cui hai lavorato','Esperienza nel premium / Lusso','Esperienze rilevanti con clienti','Certificazioni','Informazioni su sostenibilità / Conformità','Mercati che desideri sviluppare','Breve presentazione','URL del profilo aziendale / Presentazione / Lookbook','Località','Lingue','Area di competenza','Anni di esperienza','Disponibilità','Libero professionista / Società','URL del portfolio','URL LinkedIn','Tariffa giornaliera / Compenso abituale per progetto'],
 groups:['Il tuo progetto','Azienda e contatti','Competenze tecniche','Produzione e sviluppo','Mercati ed esperienza','Standard e conformità','Ambizioni commerciali','Il tuo profilo','Le tue competenze'],
 intro:'Questo modulo prepara una bozza di email da rivedere e inviare con la tua applicazione di posta. Il sito non invia né memorizza i tuoi dati.',requiredNote:'I campi contrassegnati con * sono obbligatori. Gli altri sono facoltativi.',optional:'facoltativo',choose:'Seleziona un’area',consent:'Acconsento a condividere queste informazioni via email con MILENA PEREIRA LIMITED affinché possa valutare e rispondere alla mia richiesta. Comprendo che questo modulo non invia né memorizza i miei dati.',privacy:'I dati inseriti rimangono su questa pagina fino alla chiusura o all’aggiornamento. Non vengono salvati in un database né nella memoria del browser. Dopo l’invio di un’email, il contenuto è trattato dai fornitori di posta coinvolti. Per domande sulla privacy: milena@milenapereira.co.',urlHint:'Inserisci un link completo con http:// o https://. I documenti si condividono tramite URL; questo sito non carica file.',experienceHint:'Condividi soltanto esperienze e informazioni che sei autorizzato a divulgare.',
 submit:{brandEnquiry:'Parliamo del tuo progetto',manufacturerApplication:'Invia la candidatura produttori',specialistApplication:'Invia la candidatura specialisti'},beforeSubmit:'Passaggio successivo: rivedere la bozza di email. Il modulo non invia nulla.',errorTitle:'Controlla i seguenti campi.',errors:{required:'Compila questo campo.',email:'Inserisci un indirizzo email valido.',url:'Inserisci un URL http:// o https:// completo, senza credenziali di accesso.',number:'Inserisci un numero da 0 a 80.',tooLong:'Usa al massimo {max} caratteri.',consent:'Conferma di aver compreso come verrà gestita la richiesta.'},ready:'La bozza di email è pronta',notSent:'Questo sito non ha inviato né memorizzato nulla. Rivedi la bozza e inviala dalla tua applicazione di posta.',longDraft:'Per questa candidatura dettagliata, copia la bozza qui sotto e incollala nell’email. Il link compila solo il destinatario e l’oggetto.',shortDraft:'Apri l’email preparata qui sotto oppure copia la bozza nel tuo servizio di posta preferito.',openEmail:'Apri email',copy:'Copia la bozza',copied:'Bozza copiata. Incollala nell’email e inviala quando vuoi.',copyError:'Copia automatica non disponibile. Seleziona e copia manualmente la bozza qui sotto.',edit:'Modifica i dati',draftLabel:'La tua bozza di email',noScript:'Abilita JavaScript per utilizzare il modulo. Puoi anche scrivere direttamente a milena@milenapereira.co.'
 }),
 es:form({
 titles:{brandEnquiry:'Consulta para marcas',manufacturerApplication:'Solicitud para fabricantes',specialistApplication:'Solicitud para la red de especialistas'},
 labels:['Nombre','Marca / Empresa','Cargo / Función','Correo electrónico','Sitio web','Categorías de producto','¿Cómo podemos ayudarte?','Plazos del proyecto','Presupuesto orientativo / Alcance del proyecto','Teléfono / WeChat','País','Ciudad','Especialidades de fabricación','Conocimientos de materiales / Hilados','Maquinaria / Técnicas especializadas','Cantidad mínima de pedido (MOQ)','Capacidad de producción','Plazos habituales','Taller de muestras / Capacidad de desarrollo','Mercados actuales / Mercados de experiencia','Experiencia en premium / Lujo','Experiencia relevante con clientes','Certificaciones','Información de sostenibilidad / Cumplimiento','Mercados que deseas desarrollar','Breve presentación','URL del perfil de empresa / Presentación / Lookbook','Ubicación','Idiomas','Área de especialidad','Años de experiencia','Disponibilidad','Profesional independiente / Empresa','URL del portfolio','URL de LinkedIn','Tarifa diaria / Honorarios habituales por proyecto'],
 groups:['Tu proyecto','Empresa y contacto','Capacidades técnicas','Producción y desarrollo','Mercados y experiencia','Normas y cumplimiento','Ambiciones comerciales','Tu perfil','Tu especialidad'],
 intro:'Este formulario prepara un borrador de correo para que lo revises y lo envíes desde tu aplicación de correo. El sitio no envía ni almacena tus datos.',requiredNote:'Los campos con * son obligatorios. Los demás son opcionales.',optional:'opcional',choose:'Selecciona un área',consent:'Acepto compartir estos datos por correo con MILENA PEREIRA LIMITED para que pueda evaluar y responder a mi consulta. Entiendo que este formulario no envía ni almacena mi información.',privacy:'Los datos introducidos permanecen en esta página hasta que salgas o la actualices. No se guardan en una base de datos ni en el almacenamiento del navegador. Una vez enviado el correo, su contenido es tratado por los proveedores de correo implicados. Para consultas de privacidad: milena@milenapereira.co.',urlHint:'Introduce un enlace completo con http:// o https://. Los documentos se comparten mediante URL; este sitio no carga archivos.',experienceHint:'Comparte únicamente experiencias e información que tengas autorización para divulgar.',
 submit:{brandEnquiry:'Hablemos de tu proyecto',manufacturerApplication:'Enviar solicitud de fabricante',specialistApplication:'Enviar solicitud de especialista'},beforeSubmit:'Siguiente paso: revisar el borrador del correo. Este formulario no envía nada.',errorTitle:'Revisa los siguientes campos.',errors:{required:'Completa este campo.',email:'Introduce una dirección de correo válida.',url:'Introduce una URL http:// o https:// completa, sin credenciales de acceso.',number:'Introduce un número entre 0 y 80.',tooLong:'Utiliza un máximo de {max} caracteres.',consent:'Confirma que entiendes cómo se gestionará tu consulta.'},ready:'Tu borrador de correo está listo',notSent:'Este sitio no ha enviado ni almacenado nada. Revisa el borrador y envíalo desde tu aplicación de correo.',longDraft:'Para esta solicitud detallada, copia el borrador de abajo y pégalo en tu correo. El enlace solo incluye el destinatario y el asunto.',shortDraft:'Abre el correo preparado a continuación o copia el borrador en tu servicio de correo preferido.',openEmail:'Abrir correo',copy:'Copiar borrador',copied:'Borrador copiado. Pégalo en tu correo y envíalo cuando quieras.',copyError:'No se pudo copiar automáticamente. Selecciona y copia el borrador de abajo.',edit:'Editar datos',draftLabel:'Tu borrador de correo',noScript:'Activa JavaScript para utilizar el formulario. También puedes escribir directamente a milena@milenapereira.co.'
 }),
 zh:form({
 titles:{brandEnquiry:'品牌项目咨询',manufacturerApplication:'制造商合作申请',specialistApplication:'专业协作网络申请'},
 labels:['姓名','品牌／公司名称','职务','电子邮箱','网站','产品品类','您需要哪些支持？','项目时间安排','预估预算／项目范围','电话／微信','国家','城市','制造专长','材料／纱线专长','设备／专业工艺','最低起订量（MOQ）','生产能力','常规交期','样品室／开发能力','现有市场／曾服务的市场','高端／奢侈品经验','相关客户合作经验','认证','可持续发展／合规信息','希望拓展的市场','简要介绍','公司介绍／产品册链接','所在地','工作语言','专业领域','从业年限','可合作时间','自由职业／公司经营状态','作品集链接','LinkedIn 链接','常规日费率／项目报价'],
 groups:['您的项目','公司与联系人','技术能力','生产与开发','市场与经验','标准与合规','商业目标','个人信息','专业经验'],
 intro:'本表单将生成邮件草稿，供您确认后通过自己的邮件应用发送。网站不会发送或保存您的信息。',requiredNote:'标有 * 的字段为必填，其余为选填。',optional:'选填',choose:'请选择专业领域',consent:'我同意通过邮件向 MILENA PEREIRA LIMITED 提供这些信息，以便其评估并回复我的咨询。我理解本表单不会发送或保存我的信息。',privacy:'填写内容仅保留在当前页面，离开或刷新页面后即不再保留。信息不会写入数据库或浏览器存储。邮件发送后，其内容由相关邮件服务商处理。如有隐私方面的问题，请联系 milena@milenapereira.co。',urlHint:'请输入以 http:// 或 https:// 开头的完整链接。资料通过链接分享，本网站不上传文件。',experienceHint:'请仅提供您有权公开或披露的经验与信息。',
 submit:{brandEnquiry:'洽谈项目',manufacturerApplication:'提交制造商合作申请',specialistApplication:'提交专业人士申请'},beforeSubmit:'下一步：确认邮件草稿。本表单不会发送任何信息。',errorTitle:'请检查以下字段。',errors:{required:'请填写此项。',email:'请输入有效的电子邮箱地址。',url:'请输入完整的 http:// 或 https:// 链接，且不包含登录信息。',number:'请输入 0 至 80 之间的数字。',tooLong:'请将内容控制在 {max} 个字符以内。',consent:'请确认您已了解咨询信息的处理方式。'},ready:'邮件草稿已生成',notSent:'本网站尚未发送或保存任何信息。请确认草稿后，通过您自己的邮件应用发送。',longDraft:'申请内容较长，请复制下方草稿并粘贴到邮件中。邮件链接仅填写收件人及主题。',shortDraft:'请打开下方已准备的邮件，或将草稿复制到您常用的邮件服务中。',openEmail:'打开邮件',copy:'复制草稿',copied:'草稿已复制。请粘贴到邮件中，确认后发送。',copyError:'无法自动复制。请手动选择并复制下方草稿。',edit:'修改信息',draftLabel:'您的邮件草稿',noScript:'请启用 JavaScript 以使用表单。您也可以直接发送邮件至 milena@milenapereira.co。'
 }),
};
