export default {
 en: {
  aboutBody: 'My experience includes work with Alexander McQueen and Casablanca Paris, senior product leadership and CPO roles.',
  intro: 'Helping fashion brands develop stronger products and manufacturing strategies. Helping manufacturers strengthen their offer and reach international markets.',
  book: 'Book a call', bookIntro: 'Book a call', enquiry: 'Send a project enquiry',
  bookingNote: 'Online booking is not yet available. Email me to arrange a 30-minute introductory call.',
  heroBookingNote: 'Online booking is not yet available. Go to Contact to arrange a call.',
  callSubject: '30-minute introductory call request',
  aboutTitle: '18 YEARS ACROSS FASHION, LUXURY, PRODUCT AND MANUFACTURING.',
  aboutLocation: 'I’m based between London and Paris and work internationally.',
  contactIntro: 'For fashion brands developing their next collection and manufacturers strengthening their offer or expanding into new markets.',
 },
 fr: {
  aboutBody: 'J’ai travaillé chez Alexander McQueen et Casablanca Paris et occupé des postes de direction produit et de CPO.',
  intro: 'J’accompagne les marques de mode dans le développement produit et la fabrication. J’aide les fabricants à développer leurs collections et à accéder à de nouveaux marchés.',
  book: 'Prendre rendez-vous', bookIntro: 'Prendre rendez-vous', enquiry: 'Présenter un projet',
  bookingNote: 'La réservation en ligne n’est pas encore disponible. Écrivez-moi pour convenir d’un premier échange de 30 minutes.',
  heroBookingNote: 'La réservation en ligne n’est pas encore disponible. Rendez-vous à la rubrique Contact pour convenir d’un échange.',
  callSubject: 'Demande de premier échange de 30 minutes',
  aboutTitle: '18 ANS DANS LA MODE, LE LUXE, LE PRODUIT ET LA FABRICATION.',
  aboutLocation: 'Je suis basée entre Londres et Paris et je travaille à l’international.',
  contactIntro: 'Pour les marques qui préparent leur prochaine collection et les fabricants qui développent leur offre ou abordent de nouveaux marchés.',
 },
 pt: {
  aboutBody: 'Minha experiência inclui atuação na Alexander McQueen e na Casablanca Paris e cargos de liderança sênior de produto e CPO.',
  intro: 'Trabalho com marcas de moda no desenvolvimento de produto e na fabricação. Ajudo fabricantes a desenvolver coleções e alcançar novos mercados.',
  book: 'Agendar uma conversa', bookIntro: 'Agendar uma conversa', enquiry: 'Enviar consulta de projeto',
  bookingNote: 'O agendamento online ainda não está disponível. Escreva para mim para marcar uma conversa inicial de 30 minutos.',
  heroBookingNote: 'O agendamento online ainda não está disponível. Vá à seção Contato para marcar uma conversa.',
  callSubject: 'Solicitação de conversa inicial de 30 minutos',
  aboutTitle: '18 ANOS EM MODA, LUXO, PRODUTO E FABRICAÇÃO.',
  aboutLocation: 'Trabalho entre Londres e Paris, com atuação internacional.',
  contactIntro: 'Para marcas que desenvolvem sua próxima coleção e fabricantes que fortalecem sua oferta ou entram em novos mercados.',
 },
 it: {
  aboutBody: 'Ho lavorato presso Alexander McQueen e Casablanca Paris e ricoperto ruoli di direzione prodotto e di CPO.',
  intro: 'Lavoro con i brand di moda sullo sviluppo prodotto e sulla manifattura. Aiuto i produttori a sviluppare collezioni e ad accedere a nuovi mercati.',
  book: 'Prenota un colloquio', bookIntro: 'Prenota un colloquio', enquiry: 'Parliamo di un progetto',
  bookingNote: 'La prenotazione online non è ancora disponibile. Scrivimi per concordare un colloquio introduttivo di 30 minuti.',
  heroBookingNote: 'La prenotazione online non è ancora disponibile. Vai ai contatti per concordare un colloquio.',
  callSubject: 'Richiesta di colloquio introduttivo di 30 minuti',
  aboutTitle: '18 ANNI TRA MODA, LUSSO, PRODOTTO E MANIFATTURA.',
  aboutLocation: 'Lavoro tra Londra e Parigi, con incarichi internazionali.',
  contactIntro: 'Parliamo della prossima collezione, delle esigenze produttive o dei piani per un nuovo mercato.',
 },
 es: {
  aboutBody: 'He trabajado en Alexander McQueen y Casablanca Paris y ocupado puestos de dirección sénior de producto y CPO.',
  intro: 'Trabajo con marcas de moda en desarrollo de producto y fabricación. Ayudo a los fabricantes a desarrollar colecciones y acceder a nuevos mercados.',
  book: 'Concertar una llamada', bookIntro: 'Concertar una llamada', enquiry: 'Consultar un proyecto',
  bookingNote: 'La reserva online aún no está disponible. Escríbeme para concertar una llamada inicial de 30 minutos.',
  heroBookingNote: 'La reserva online aún no está disponible. Ve a Contacto para concertar una llamada.',
  callSubject: 'Solicitud de llamada inicial de 30 minutos',
  aboutTitle: '18 AÑOS EN MODA, LUJO, PRODUCTO Y FABRICACIÓN.',
  aboutLocation: 'Trabajo entre Londres y París, con proyectos internacionales.',
  contactIntro: 'Hablemos de tu próxima colección, tus necesidades de fabricación o tus planes para un nuevo mercado.',
 },
 zh: {
  aboutBody: '我曾在 Alexander McQueen 和 Casablanca Paris 工作，担任过高级产品管理及首席产品官（CPO）职务。',
  intro: '我为时尚品牌提供产品开发和制造方面的支持，也帮助制造商开发系列、拓展新市场。',
  book: '预约通话', bookIntro: '预约通话', enquiry: '洽谈项目',
  bookingNote: '在线预约尚未开放。请给我发邮件，安排30分钟的初步交流。',
  heroBookingNote: '在线预约尚未开放。请前往联系板块安排交流。',
  callSubject: '预约30分钟初步交流',
  aboutTitle: '18年经验，贯穿时尚、奢侈品、产品与制造。',
  aboutLocation: '我在伦敦和巴黎工作，承接国际项目。',
  contactIntro: '请介绍您的下一季系列、制造需求或新市场计划。',
 },
};
