export default {
 en: {
  aboutBody: "Product leader and consultant working across product development, manufacturing, sourcing and international business development. Experience includes Alexander McQueen, Casablanca Paris and CPO leadership.",
  intro: "Fashion product, manufacturing and business development for brands and manufacturers.",
  book: 'Book a call', bookIntro: 'Book a call', enquiry: 'Send a project enquiry',
  bookingNote: 'Online booking is not yet available. Email me to arrange a 30-minute introductory call.',
  heroBookingNote: 'Online booking is not yet available. Go to Contact to arrange a call.',
  callSubject: '30-minute introductory call request',
  aboutTitle: "18 YEARS ACROSS FASHION AND LUXURY.",
  aboutLocation: 'I’m based between London and Paris and work internationally.',
  contactIntro: 'For fashion brands developing their next collection and manufacturers strengthening their offer or expanding into new markets.',
  contactHomeTitle: "LET’S TALK.",
  contactHomeIntro: "Have a project, collection, manufacturing requirement or commercial opportunity to discuss?",
  enquiryHome: "Send an enquiry",
  navigation: ["Brands", "Manufacturers", "Work with me", "About", "Book a call"],
  audienceItems: [["I’M A BRAND", "Product development, sourcing and manufacturing."], ["I’M A MANUFACTURER", "Collections, positioning and international business development."], ["I WANT TO WORK WITH YOU", "Join the specialist and commercial network."]],
 },
 fr: {
  aboutBody: "Directrice produit et consultante en développement produit, fabrication, sourcing et développement commercial international. Expérience chez Alexander McQueen et Casablanca Paris, ainsi qu’à des postes de CPO.",
  intro: "Développement produit, fabrication et développement commercial pour les marques de mode et les fabricants.",
  book: 'Prendre rendez-vous', bookIntro: 'Prendre rendez-vous', enquiry: 'Présenter un projet',
  bookingNote: 'La réservation en ligne n’est pas encore disponible. Écrivez-moi pour convenir d’un premier échange de 30 minutes.',
  heroBookingNote: 'La réservation en ligne n’est pas encore disponible. Rendez-vous à la rubrique Contact pour convenir d’un échange.',
  callSubject: 'Demande de premier échange de 30 minutes',
  aboutTitle: "18 ANS DANS LA MODE ET LE LUXE.",
  aboutLocation: 'Je suis basée entre Londres et Paris et je travaille à l’international.',
  contactIntro: 'Pour les marques qui préparent leur prochaine collection et les fabricants qui développent leur offre ou abordent de nouveaux marchés.',
  contactHomeTitle: "PARLONS-EN.",
  contactHomeIntro: "Un projet, une collection, un besoin de fabrication ou une collaboration commerciale à discuter ?",
  enquiryHome: "Envoyer une demande",
  navigation: ["Marques", "Fabricants", "Travailler avec moi", "À propos", "Prendre rendez-vous"],
  audienceItems: [["JE SUIS UNE MARQUE", "Développement produit, sourcing et fabrication."], ["JE SUIS UN FABRICANT", "Collections, positionnement et développement commercial international."], ["JE SOUHAITE COLLABORER", "Rejoindre le réseau de spécialistes et de partenaires commerciaux."]],
 },
 pt: {
  aboutBody: "Líder de produto e consultora em desenvolvimento de produto, fabricação, sourcing e desenvolvimento de negócios internacionais. Experiência na Alexander McQueen, na Casablanca Paris e em cargos de CPO.",
  intro: "Desenvolvimento de produto, fabricação e desenvolvimento de negócios para marcas de moda e fabricantes.",
  book: 'Agendar uma conversa', bookIntro: 'Agendar uma conversa', enquiry: 'Enviar consulta de projeto',
  bookingNote: 'O agendamento online ainda não está disponível. Escreva para mim para marcar uma conversa inicial de 30 minutos.',
  heroBookingNote: 'O agendamento online ainda não está disponível. Vá à seção Contato para marcar uma conversa.',
  callSubject: 'Solicitação de conversa inicial de 30 minutos',
  aboutTitle: "18 ANOS NA MODA E NO LUXO.",
  aboutLocation: 'Trabalho entre Londres e Paris, com atuação internacional.',
  contactIntro: 'Para marcas que desenvolvem sua próxima coleção e fabricantes que fortalecem sua oferta ou entram em novos mercados.',
  contactHomeTitle: "VAMOS CONVERSAR.",
  contactHomeIntro: "Tem um projeto, uma coleção, uma necessidade de fabricação ou uma proposta comercial para discutir?",
  enquiryHome: "Enviar uma consulta",
  navigation: ["Marcas", "Fabricantes", "Trabalhe comigo", "Sobre", "Agendar conversa"],
  audienceItems: [["SOU UMA MARCA", "Desenvolvimento de produto, sourcing e fabricação."], ["SOU UM FABRICANTE", "Coleções, posicionamento e desenvolvimento de negócios internacionais."], ["QUERO TRABALHAR COM VOCÊ", "Faça parte da rede de especialistas e parceiros comerciais."]],
 },
 it: {
  aboutBody: "Responsabile prodotto e consulente in sviluppo prodotto, manifattura, sourcing e sviluppo commerciale internazionale. Esperienza presso Alexander McQueen e Casablanca Paris e in ruoli di CPO.",
  intro: "Sviluppo prodotto, manifattura e sviluppo commerciale per brand di moda e produttori.",
  book: 'Prenota un colloquio', bookIntro: 'Prenota un colloquio', enquiry: 'Parliamo di un progetto',
  bookingNote: 'La prenotazione online non è ancora disponibile. Scrivimi per concordare un colloquio introduttivo di 30 minuti.',
  heroBookingNote: 'La prenotazione online non è ancora disponibile. Vai ai contatti per concordare un colloquio.',
  callSubject: 'Richiesta di colloquio introduttivo di 30 minuti',
  aboutTitle: "18 ANNI NELLA MODA E NEL LUSSO.",
  aboutLocation: 'Lavoro tra Londra e Parigi, con incarichi internazionali.',
  contactIntro: 'Parliamo della prossima collezione, delle esigenze produttive o dei piani per un nuovo mercato.',
  contactHomeTitle: "PARLIAMONE.",
  contactHomeIntro: "Hai un progetto, una collezione, un’esigenza produttiva o una proposta commerciale da discutere?",
  enquiryHome: "Invia una richiesta",
  navigation: ["Brand", "Produttori", "Lavora con me", "Chi sono", "Prenota un colloquio"],
  audienceItems: [["SONO UN BRAND", "Sviluppo prodotto, sourcing e manifattura."], ["SONO UN PRODUTTORE", "Collezioni, posizionamento e sviluppo commerciale internazionale."], ["VORREI COLLABORARE", "Entra nella rete di specialisti e partner commerciali."]],
 },
 es: {
  aboutBody: "Directora de producto y consultora en desarrollo de producto, fabricación, sourcing y desarrollo de negocio internacional. Experiencia en Alexander McQueen, Casablanca Paris y puestos de CPO.",
  intro: "Desarrollo de producto, fabricación y desarrollo de negocio para marcas de moda y fabricantes.",
  book: 'Concertar una llamada', bookIntro: 'Concertar una llamada', enquiry: 'Consultar un proyecto',
  bookingNote: 'La reserva online aún no está disponible. Escríbeme para concertar una llamada inicial de 30 minutos.',
  heroBookingNote: 'La reserva online aún no está disponible. Ve a Contacto para concertar una llamada.',
  callSubject: 'Solicitud de llamada inicial de 30 minutos',
  aboutTitle: "18 AÑOS EN MODA Y LUJO.",
  aboutLocation: 'Trabajo entre Londres y París, con proyectos internacionales.',
  contactIntro: 'Hablemos de tu próxima colección, tus necesidades de fabricación o tus planes para un nuevo mercado.',
  contactHomeTitle: "HABLEMOS.",
  contactHomeIntro: "¿Tienes un proyecto, una colección, una necesidad de fabricación o una propuesta comercial que quieras comentar?",
  enquiryHome: "Enviar una consulta",
  navigation: ["Marcas", "Fabricantes", "Trabaja conmigo", "Sobre mí", "Concertar una llamada"],
  audienceItems: [["SOY UNA MARCA", "Desarrollo de producto, sourcing y fabricación."], ["SOY UN FABRICANTE", "Colecciones, posicionamiento y desarrollo de negocio internacional."], ["QUIERO COLABORAR", "Forma parte de la red de especialistas y socios comerciales."]],
 },
 zh: {
  aboutBody: "产品负责人及顾问，专注于产品开发、制造、采购及国际业务拓展。曾任职于 Alexander McQueen 和 Casablanca Paris，并担任过首席产品官（CPO）。",
  intro: "为时尚品牌和制造商提供产品开发、制造及业务拓展服务。",
  book: '预约通话', bookIntro: '预约通话', enquiry: '洽谈项目',
  bookingNote: '在线预约尚未开放。请给我发邮件，安排30分钟的初步交流。',
  heroBookingNote: '在线预约尚未开放。请前往联系板块安排交流。',
  callSubject: '预约30分钟初步交流',
  aboutTitle: "18年时尚与奢侈品行业经验。",
  aboutLocation: '我在伦敦和巴黎工作，承接国际项目。',
  contactIntro: '请介绍您的下一季系列、制造需求或新市场计划。',
  contactHomeTitle: "聊聊您的计划。",
  contactHomeIntro: "您是否有项目、系列开发、制造需求或商务合作计划希望洽谈？",
  enquiryHome: "发送咨询",
  navigation: ["品牌", "制造商", "与我合作", "关于我", "预约通话"],
  audienceItems: [["我是品牌方", "产品开发、采购与制造。"], ["我是制造商", "系列开发、定位与国际业务拓展。"], ["我希望参与合作", "加入专业人才与商务合作网络。"]],
 },
};
