const servicesBrands=['Product Development','Fabric & Material Sourcing','Factory Sourcing','Sampling & Production','Costing & Negotiation','Manufacturing Strategy'];
const servicesMakers=['Business Development','International Market Expansion','Brand Introductions','Commercial Representation','Category Development'];
export default function Home(){return <main>
<header><a className="brand" href="#top">MILENA PEREIRA</a><nav><a href="#expertise">Expertise</a><a href="#network">Network</a><a href="#about">About</a><a href="#contact">Private Consultation</a></nav></header>
<section className="hero" id="top"><div className="eyebrow">PRODUCT · MANUFACTURING · BUSINESS DEVELOPMENT</div><h1>FROM CONCEPT<br/>TO PRODUCTION.</h1><div className="heroBottom"><p>Global product development and manufacturing consultancy for fashion brands and suppliers.</p><a className="arrow" href="#contact">DISCUSS A PROJECT ↗</a></div><div className="places">CHINA · PORTUGAL · ITALY · WORLDWIDE</div></section>
<section className="statement"><p className="kicker">THE RIGHT PRODUCT STARTS WITH THE RIGHT PARTNER.</p><h2>I connect creative vision with the right materials, technical expertise and manufacturing capability.</h2><p className="body">Working directly with brands, factories, mills and specialist suppliers, I support product from initial development through sourcing, sampling, costing and production — building commercially relevant solutions around each project.</p></section>
<section className="expertise" id="expertise"><div className="sectionTitle"><span>01</span><h3>EXPERTISE</h3></div><div className="columns"><div><h4>FOR BRANDS</h4>{servicesBrands.map((x,i)=><div className="service" key={x}><span>0{i+1}</span>{x}</div>)}</div><div><h4>FOR MANUFACTURERS</h4>{servicesMakers.map((x,i)=><div className="service" key={x}><span>0{i+1}</span>{x}</div>)}</div></div></section>
<section className="network" id="network"><div className="sectionTitle light"><span>02</span><h3>GLOBAL NETWORK</h3></div><div className="networkIntro"><h2>BUILT ON<br/>THE GROUND.</h2><p>A trusted international network shaped around product, quality, capability, scale and commercial fit — not a one-size-fits-all supplier list.</p></div><div className="countries"><article><b>CHINA</b><p>Advanced manufacturing, technical product and specialist capabilities.</p></article><article><b>PORTUGAL</b><p>Premium garment manufacturing, jersey, knitwear and specialist production.</p></article><article><b>ITALY</b><p>Luxury materials, specialist craftsmanship and premium manufacturing.</p></article><article><b>GLOBAL</b><p>The right partner selected around the requirements of each project.</p></article></div></section>
<section className="about" id="about"><div className="sectionTitle"><span>03</span><h3>ABOUT</h3></div><div className="aboutGrid"><h2>PRODUCT.<br/>MANUFACTURING.<br/>BUSINESS.</h2><div><p>Milena Pereira is an independent product development, manufacturing and business development consultant working across the international fashion industry.</p><p>Her work sits between creative, product and commercial teams — helping brands turn ideas into viable product and helping manufacturers build meaningful relationships with international markets.</p><p>With experience across luxury fashion, product leadership and global supplier development, her approach is practical, product-led and built around long-term partnerships.</p></div></div></section>
<section className="contact" id="contact"><div className="sectionTitle light"><span>04</span><h3>PRIVATE CONSULTATION</h3></div><h2>LET'S TALK<br/>PRODUCT.</h2><p>Need a factory? Looking for a specific fabric? Developing a new category? Facing a production challenge? Or looking to expand your manufacturing business into new markets?</p><a className="contactButton" href="mailto:hello@placeholder.com?subject=Private%20Consultation">START A CONVERSATION ↗</a><small>Contact email will be connected before public launch.</small></section>
<footer><span>MILENA PEREIRA</span><span>GLOBAL PRODUCT & MANUFACTURING CONSULTANCY</span><span>© 2026</span></footer>
</main>}
